language: python
python:
    - "2.7"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - deps='pysam'
  - conda create -q -c bioconda -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
  - source activate test-environment

script:
    - cd test && ./test.sh
    - python test_svtyper.py

# # command to install dependencies
# install:
#   # We do this conditionally because it saves us some downloading if the
#   # version is the same.
#   - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
#       wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
#     else
#       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#     fi
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - export PATH="$HOME/miniconda/bin:$PATH"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   - conda update -q conda
#   # Useful for debugging any issues with conda
#   - conda info -a

#   - deps='libgfortran pip nose coverage statsmodels numpy pandas scipy'
#   - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
#   - source activate test-environment

# # command to run tests
# script: 
# # FIXME If these were modules, this shouldn't be necessary
#     nosetests --all-modules --traverse-namespace --with-coverage --cover-inclusive --with-id -v
# after_success:
#     - pip install coveralls
#     - coveralls
